from django.http import HttpResponse
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

from .forms import SoilReportForm
from .models import SoilReport
from .utils import analyze_soil


# -------------------------------
# HEADER & FOOTER FOR PDF
# -------------------------------

def add_header_footer(canvas, doc):

    width, height = A4

    # Header
    canvas.setFont("Helvetica-Bold", 14)
    canvas.drawString(2 * cm, height - 2 * cm, "AgriSense Soil Analysis Report")

    canvas.setFont("Helvetica", 9)
    canvas.drawRightString(width - 2 * cm, height - 2 * cm, "Smart Agriculture Platform")

    # Footer
    canvas.setFont("Helvetica", 9)
    canvas.drawString(2 * cm, 1.5 * cm, "Generated by AgriSense")

    canvas.drawRightString(width - 2 * cm, 1.5 * cm, f"Page {doc.page}")


# -------------------------------
# UPLOAD SOIL REPORT
# -------------------------------

@login_required
def upload_soil_report(request):
    if request.method == 'POST':
        form = SoilReportForm(request.POST)

        if form.is_valid():

            soil_report = form.save(commit=False)
            soil_report.user = request.user

            crop, fertilizer = analyze_soil(
                soil_report.ph,
                soil_report.nitrogen,
                soil_report.phosphorus,
                soil_report.potassium
            )

            soil_report.crop_recommendation = crop
            soil_report.fertilizer_advice = fertilizer
            soil_report.save()

            return redirect('soil_result', pk=soil_report.pk)

    else:
        form = SoilReportForm()

    return render(request, 'soil/upload.html', {'form': form})


# -------------------------------
# SHOW RESULT
# -------------------------------

@login_required
def soil_result(request, pk):
    report = get_object_or_404(SoilReport, pk=pk, user=request.user)
    return render(request, 'soil/result.html', {'report': report})


# -------------------------------
# HISTORY
# -------------------------------

@login_required
def soil_history(request):
    reports = SoilReport.objects.filter(user=request.user).order_by('-created_at')
    return render(request, 'soil/history.html', {'reports': reports})


# -------------------------------
# DELETE REPORT
# -------------------------------

@login_required
def delete_soil_report(request, report_id):
    report = get_object_or_404(SoilReport, id=report_id, user=request.user)
    report.delete()
    return redirect('soil_history')


# -------------------------------
# DOWNLOAD PDF
# -------------------------------

@login_required
def download_soil_pdf(request, pk):

    report = get_object_or_404(SoilReport, pk=pk, user=request.user)

    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'attachment; filename="soil_report_{report.id}.pdf"'

    doc = SimpleDocTemplate(
        response,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=80,
        bottomMargin=60
    )

    styles = getSampleStyleSheet()
    elements = []

    # Title
    elements.append(Paragraph("Soil Analysis Report", styles['Title']))
    elements.append(Spacer(1, 20))

    # Farmer Info
    elements.append(Paragraph(f"<b>Farmer Name:</b> {report.user.username}", styles['Normal']))
    elements.append(Paragraph(f"<b>Report Date:</b> {report.created_at}", styles['Normal']))

    elements.append(Spacer(1, 20))

    # Soil Data
    elements.append(Paragraph("<b>Soil Parameters</b>", styles['Heading2']))
    elements.append(Spacer(1, 10))

    elements.append(Paragraph(f"pH Level: {report.ph}", styles['Normal']))
    elements.append(Paragraph(f"Nitrogen: {report.nitrogen}", styles['Normal']))
    elements.append(Paragraph(f"Phosphorus: {report.phosphorus}", styles['Normal']))
    elements.append(Paragraph(f"Potassium: {report.potassium}", styles['Normal']))
    elements.append(Paragraph(f"Organic Carbon: {report.organic_carbon}", styles['Normal']))

    elements.append(Spacer(1, 20))

    # Recommendations
    elements.append(Paragraph("<b>Recommendations</b>", styles['Heading2']))
    elements.append(Spacer(1, 10))

    elements.append(Paragraph(f"Recommended Crops: {report.crop_recommendation}", styles['Normal']))
    elements.append(Paragraph(f"Fertilizer Advice: {report.fertilizer_advice}", styles['Normal']))

    doc.build(
        elements,
        onFirstPage=add_header_footer,
        onLaterPages=add_header_footer
    )

    return response